import localFont from 'next/font/local';
import "./globals.css";

const magilio = localFont({
  src: [
    {
      path: '../public/fonts/magilio/magilio.ttf',
      weight: '400'
    },
  ],
  variable: '--magilio'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${magilio.variable}`}>{children}</body>
    </html>
  );
}
